### ISSUE TITLE
Minimal usage documentation

### ISSUE THREAD

**Issue by tomdyson** [l1f7/wagtail_uplift#5]
Is it on PyPI? How do you apply the skin? What Wagtail versions are supported? 

Thanks!

**Comment by KalobTaulien** [comment]
Hey Tom! 
Yep, it's on PyPi, but it's an older version. Here's the link: https://pypi.org/project/wagtail-uplift/

To apply the skin add `'wagtail_uplift',` to your `INSTALLED_APPS`. 

Works with most versions of wagtail, including the latest. Can't speak for v2.2 though since we never got 2.2 running with Django and jumped right over that one.

**Comment by hyshka** [comment]
Thanks for the addition @tomdyson!
